### ISSUE TITLE
Céupedia is broken (again :P)

### ISSUE THREAD

**Issue by JobLeonard** [fsantanna/ceu-site#3]
Various links result in:

> Fatal error: Call to undefined function wfLoadExtensionMessages() in /home/fsantanna/site/wiki/extensions/EmbedVideo/EmbedVideo.hooks.php on line 76

For example: http://www.ceu-lang.org/wiki/index.php?title=TinyOS

**Comment by fsantanna** [comment]
Thanks, hope it is fixed. Some automatic updates in dreamhost.

**Comment by JobLeonard** [comment]
FWIW, website loads again for me :)
