### ISSUE TITLE
Clicking the Index button causes the previous lesson to be loaded

### ISSUE THREAD

**Issue by calmattoso** [fsantanna/ceu-site#4]
When clicking the `Index` button to open the modal with the list of all available lessons the event is also captured by the handler for the `Previous` button, which causes the previous lesson to be loaded. Even though the modal opens as expected, loading the previous lesson is an unexpected behavior in response to the user action.

<img src="https://cloud.githubusercontent.com/assets/569859/14757708/e1174a00-08cc-11e6-9cdd-baa918f20916.gif" align="left" width="300" >

**Comment by fsantanna** [comment]
Thanks! Fixed in the website.
